### ISSUE TITLE
Osprey farpoint 55 fits into a ryanair luggage?

### ISSUE THREAD

**Issue by jtomaszewski** [JohnONolan/Professionally-Homeless#2]
Hey. Thanks for sharing the materials of the book - great work so far!

> I decided that I wanted something that would be hand-baggage size no matter what airline I travelled on. This means conforming to RyanAir’s 55cm x 40cm x 20cm hand luggage restriction, which they enforce rigorously. The Farpoint 55 comes in two sizes, Small and Medium (you get different sizes based on your height, to fit you best). While the “55” in “Farpoint 55” stands for 55 litres, the smaller of the two sizes is actually only 52 litres and, when the daypack is contained within the carefully packed main compartment rather than strapped to the outside… fits exactly into the bag-cages which airlines like RyanAir and easyJet use to check the size of your luggage.

Just wanted to check if I understood correctly. There are no problems about 'sneaking in' the [Farpoint 55 S/M](http://www.ospreyeurope.com/pl_en/view-by-series/travel/farpoint-series/farpoint-55) through f.e. RyanAir luggage limits? Its' dimensions are said to be 64 (l) x 34 (w) x 30 (d), which is a bit larger than ryanair's limits.

**Comment by JohnONolan** [comment]
@jtomaszewski Hey! Glad you're enjoying it :) The Farpoint 55 actually fits *perfectly* in RyanAir's hand-luggage-size-checker box. I've done hundreds of flights with it/them at this point and never had a single problem. That being said, if I was going to buy again today, I think I would go for the Farpoint40 now. Over the years I slowly stopped carrying heavy camera gear, got a smaller laptop, and generally found the 55 to be slightly bigger than I needed.

**Comment by jtomaszewski** [comment]
Yeah, that's what I read in most of the posts - farpoint 40 is better and if you need a daypack, you can also buy one, that fits in a pocket, in some cheap stores ;]

So propably I'll go for the farpoint 40 or tortuga v2. Thanks ;)
